# .github/workflows/main.yml
# اسم سير العمل الذي سيظهر في GitHub Actions
name: Deploy to Firebase Hosting on merge

# تحديد متى سيتم تشغيل سير العمل
on:
  push:
    branches:
      - main # يتم تشغيل سير العمل عند الدفع (push) إلى الفرع الرئيسي (main)

# تعريف المهام (Jobs) التي سيتم تنفيذها
jobs:
  build_and_deploy:
    # تحديد نوع الجهاز الافتراضي لتشغيل المهمة عليه
    runs-on: ubuntu-latest

    # خطوات تنفيذ المهمة
    steps:
      # خطوة سحب (Checkout) الكود من المستودع
      - name: Checkout source
        uses: actions/checkout@v3

      # خطوة إعداد بيئة Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # استخدام الإصدار 20 من Node.js

      # خطوة تثبيت الاعتماديات (المكتبات) من package.json
      - name: Install dependencies
        run: npm install

      # خطوة بناء Tailwind CSS - تم تصحيح المسافات البادئة هنا
      # هذه الخطوة ضرورية لتوليد ملف public/css/style.css
      - name: Build Tailwind CSS
        run: npm run build:css

      # خطوة النشر إلى Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0 # استخدام الإجراء الرسمي للنشر إلى Firebase Hosting
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}" # توكن GitHub للمصادقة مع المستودع
          # حساب خدمة Firebase المستخدم للمصادقة مع Firebase
          # تأكد من أن هذا السر (Secret) قد تم إعداده في إعدادات مستودع GitHub الخاص بك
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_WAJABATI_PWA }}"
          channelId: live # النشر إلى القناة المباشرة
          projectId: wajabati-pwa # معرف مشروع Firebase الخاص بك

